src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $username;


    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\ManyToOne(targetEntity=Role::class, inversedBy="user")
     * @ORM\JoinColumn(nullable=false)
     */
    private $role;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez remplir ce champ")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez remplir ce champ")
     */
    private $prenom;

    /**
     * @ORM\Column(type="bigint")
     * @Assert\NotBlank(message="Veuillez remplir ce champ")
     */
    // * @Assert\Regex( pattern  = "#^(77||78||76||70||75)[0-9]{9}$#",
    // *      message="Veuillez entrer un numéro de téléphone valide."
    // * )
    private $telephone;

    /**
     * @ORM\Column(type="text")
     */
    private $uuid;

    /**
     * @ORM\OneToMany(targetEntity=Resultat::class, mappedBy="user")
     */
    private $resultats;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez choisir un code pays")
     */
    private $code;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isValid;



    /**
     * @ORM\Column(type="string", length=255, nullable=true )
     */
    private $lieu;

    /**
     * @ORM\ManyToOne(targetEntity=BureauVote::class, inversedBy="user")
     */
    private $BV;

    /**
     * @ORM\ManyToOne(targetEntity=Departement::class, inversedBy="user")
     */
    private $commune;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $presse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    public function __construct()
    {
        $this->resultats = new ArrayCollection();
        $this->isValid = false;
    }


    public function getId(): ?int
    {
        return $this->id;
    }



    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return [strtoupper($this->role->getLibelle())];
    }



    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function setRole(?Role $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(?int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }


    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    


    public function __toString()
    {
        return $this->uuid;
    }

    public function getFullname()
    {
        return $this->prenom . ' ' . $this->nom;
    }

    public function getFullnameAndNumber()
    {
        return $this->telephone . ' - ' . $this->prenom . ' ' . $this->nom;
    }


    /**
     * @return Collection<int, Resultat>
     */
    public function getResultats(): Collection
    {
        return $this->resultats;
    }

    public function addResultat(Resultat $resultat): self
    {
        if (!$this->resultats->contains($resultat)) {
            $this->resultats[] = $resultat;
            $resultat->setUser($this);
        }

        return $this;
    }

    public function removeResultat(Resultat $resultat): self
    {
        if ($this->resultats->removeElement($resultat)) {
            // set the owning side to null (unless already changed)
            if ($resultat->getUser() === $this) {
                $resultat->setUser(null);
            }
        }

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function isIsValid(): ?bool
    {
        return $this->isValid;
    }

    public function setIsValid(?bool $isValid): self
    {
        $this->isValid = $isValid;

        return $this;
    }



    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

   

    public function getBV(): ?BureauVote
    {
        return $this->BV;
    }

    public function setBV(?BureauVote $BV): self
    {
        $this->BV = $BV;

        return $this;
    }

    public function getCommune(): ?Departement
    {
        return $this->commune;
    }

    public function setCommune(?Departement $commune): self
    {
        $this->commune = $commune;

        return $this;
    }

    public function getPresse(): ?string
    {
        return $this->presse;
    }

    public function setPresse(?string $presse): self
    {
        $this->presse = $presse;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Controller/JournalisteController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Resultat;
use App\Form\ResultatType;
use App\Entity\ResultatCoalition;
use App\Repository\RoleRepository;
use App\Repository\UserRepository;
use App\Repository\ResultatRepository;
use App\Repository\CoalitionRepository;
use App\Repository\BureauVoteRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\DepartementRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

/**
 * @Route("/journaliste")
 */
class JournalisteController extends AbstractController
{
    private $roleRepository;
    private $userPasswordHasher;
    private $userRepository;
    private $bureauVoteRepository;
    private $departementRepository;
    private $session;
    private $resultatRepository;
    private $coalitionRepository;
    private $slugger;
    public function __construct(RoleRepository $roleRepository, UserPasswordHasherInterface $userPasswordHasher, UserRepository $userRepository, DepartementRepository $departementRepository, BureauVoteRepository $bureauVoteRepository, SessionInterface $session, ResultatRepository $resultatRepository, CoalitionRepository $coalitionRepository, SluggerInterface $slugger)
    {
        $this->roleRepository = $roleRepository;
        $this->session = $session;
        $this->userPasswordHasher = $userPasswordHasher;
        $this->userRepository = $userRepository;
        $this->departementRepository = $departementRepository;
        $this->bureauVoteRepository = $bureauVoteRepository;
        $this->resultatRepository = $resultatRepository;
        $this->coalitionRepository = $coalitionRepository;
        $this->slugger = $slugger;
    }

    /**
     * @Route("/", name="app_journaliste")
     */
    public function index(Request $request, EntityManagerInterface $em): Response
    {
        $user = new User();
        $role = $this->roleRepository->findOneBy(["libelle" => "ROLE_JOURNALISTE"]);

        $form = $this->createFormBuilder()
            ->add('nom', TextType::class, [
                'label' => 'Nom',
                'attr' => [
                    'placeholder' => 'Entrez le nom',
                ],
                'constraints' => new NotBlank([
                    'message' => 'Veuillez entrer le nom.'
                ]),
            ])
            ->add('prenom', TextType::class, [
                'label' => 'Prénom',
                'attr' => [
                    'placeholder' => 'Entrez le prénom',
                ],
                'constraints' => new NotBlank([
                    'message' => 'Veuillez entrer le prénom.'
                ]),
            ])
            ->add('presse', TextType::class, [
                'label' => 'Organe de presse',
                'attr' => [
                    'placeholder' => 'Entrez l\'organe de presse',
                ],
                'constraints' => new NotBlank([
                    'message' => 'Veuillez entrer l\'organe de presse.'
                ]),
            ])
            ->add('check', CheckboxType::class, [
                'label' => 'J\'accepte les termes et conditions',
                'constraints' => new NotBlank([
                    'message' => 'Veuillez accepter les termes et conditions.'
                ]),
            ])
            ->add('telephone', IntegerType::class, [
                'label' => 'Numéro de téléphone',
                'attr' => [
                    'placeholder' => 'Entrez le numéro de téléphone',
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Merci de saisir votre numéro de téléphone sans espace.'
                    ]),
                    new Regex([
                        'pattern'  => '#^(77||78||76||70||75)[0-9]{9}$#',
                        'message' => 'Veuillez entrer un numéro de téléphone valide.',
                    ]),
                ],
            ])
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'invalid_message' => 'Les deux mots de passe ne sont pas identiques.',
                'options' => ['attr' => ['class' => 'password-field']],
                'required' => true,
                'trim' => true,
                'first_options'  => ['label' => 'Mot de passe', 'attr' => [
                    'placeholder' => "Entrer le mot de passe"
                ]],
                'second_options' => ['label' => 'Confirmez le mot de passe', 'attr' => [
                    'placeholder' => "Veuillez confirmer le mot de passe"
                ]],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Merci de saisir le mot de passe.'
                    ]),
                ],
            ])

            ->getForm();
        $form->handleRequest($request);
        $usersAll = $this->userRepository->findAll();
        if ($form->isSubmitted() && $form->isValid()) {
            $telephone =  $form->get('telephone')->getData();
            $nom = $form->get('nom')->getData();
            $prenom = $form->get('prenom')->getData();
            $password = $form->get('password')->getData();
            $presse = $form->get('presse')->getData();
            foreach ($usersAll as $value) {
                if ($value->getTelephone() === (int)(221 . $telephone)) {
                    $this->addFlash('error', 'Ce numéro de téléphone existe dèja !');
                    return $this->redirectToRoute('app_journaliste', [], Response::HTTP_SEE_OTHER);
                }
            }
            $user->setRole($role);
            $user->setUuid($password);
            $user->setCode("SN");
            $user->setNom($nom);
            $user->setPresse($presse);
            $user->setPrenom($prenom);
            $user->setSlug($this->slugger->slug(trim(221 . $telephone)));
            $user->setTelephone(trim(221 . $telephone));
            $user->setPassword(
                $this->userPasswordHasher->hashPassword(
                    $user,
                    $password
                )
            );
            $user->setUsername($telephone);
            $em->persist($user);
            $em->flush();
            $this->addFlash('success', 'Votre inscription a réussi avec succès. Vous allez utiliser votre numéro de téléphone et votre mot de passe pour vous connecter.');
            return $this->redirectToRoute('app_success_journaliste', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('journaliste/index.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/add-circonscription", name="app_journaliste_circonscription_add")
     * @IsGranted("ROLE_JOURNALISTE")
     */
    public function add_journaliste(Request $request)
    {
        $ressultDepartements = [];
        $departements = $this->departementRepository->findBy([], []);
        foreach ($departements as $key => $value) {
            $ressultDepartements[$value->getNom()] = $value->getNom();
        }
        $dt =  $this->session->get("circonscription", []);
        // dd($ressultDepartements);
        $form = $this->createFormBuilder()
            ->add('circonscription', ChoiceType::class, [
                'label' => false,
                'placeholder' => 'Choisir le département',
                'choices' => $ressultDepartements,
                'data' => $dt ? $dt['circonscription'] : '',
                // 'class' => Departement::class,
                'constraints' => new NotBlank([
                    'message' => 'Veuillez choisir le département.'
                ]),
            ])
            ->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $data = $form->getData();
            $this->session->set("circonscription", $data);
            // $this->addFlash('success', 'Le partenaire a été bien ajouté');
            return $this->redirectToRoute('app_circonscription_commune_add', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('journaliste/add-circonscription.html.twig', [
            'form' => $form->createView(),
            'data' => $dt
        ]);
    }

    /**
     * @Route("/add-commune", name="app_circonscription_commune_add")
     * @IsGranted("ROLE_JOURNALISTE")
     */
    public function addcommune(Request $request): Response
    {
        $departement = $this->session->get("circonscription", []);
        if ($departement == []) {
            return $this->redirectToRoute('app_journaliste_circonscription_add', [], Response::HTTP_SEE_OTHER);
        }
        $communes  = $this->departementRepository->findBy(["nom" => $departement['circonscription']]);
        $com = [];
        foreach ($communes as $key => $value) {
            $com[$value->getCommune()] = $value->getCommune();
        }
        $dt = $this->session->get("commune", []);
        $form = $this->createFormBuilder()
            ->add('commune', ChoiceType::class, [

templates/journaliste/add-circonscription.html.twig
{% extends 'base.html.twig' %}

{% block title %}SunuLégislatives2022 | ajputer un représentant{% endblock %}

{% block body %}
<div class="container">
    {% for message in app.flashes('success') %}
    <div class="text-center alert alert-success mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
    <div class="text-center alert alert-danger mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <div class="content">
        <div class="card">
            <div class="card-header">
                <h4>Pour quel département, souhaitez-vous donner les résultats ?</h4>
            </div>
            <div class="card-body">
                {{ form_start(form, {attr: {'novalidate': 'novalidate'}}) }}
                {{ form_widget(form) }}
                {# <a href="{{path('app_journaliste')}}" class="btn btn-warning" >Précédent</a> #}
                <button class="btn btn-success">{{ button_label|default('suivant') }}</button>
                {{ form_end(form) }}
            </div>
        </div>


    </div>
</div>

{% endblock %}

templates/journaliste/add-commune.html.twig
{% extends 'base.html.twig' %}

{% block title %}SunuLégislatives2022 | ajouter un représentant{% endblock %}

{% block body %}
<div class="container">
    {% for message in app.flashes('success') %}
    <div class="text-center alert alert-success mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
    <div class="text-center alert alert-danger mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <div class="content">
        <div class="card">
            <div class="card-header">
                <h4>Pour quelle commune, souhaitez-vous donner les résultats ?</h4>
            </div>
            <div class="card-body">
                {{ form_start(form, {attr: {'novalidate': 'novalidate'}}) }}
                {{ form_widget(form) }}
                <a href="{{path('app_journaliste_circonscription_add')}}" class="btn btn-warning" >Précédent</a>
                <button class="btn btn-success">{{ button_label|default('Suivant') }}</button>
                {{ form_end(form) }}
            </div>
        </div>


    </div>
</div>

{% endblock %}

templates/journaliste/add-infos.html.twig
{% extends 'base.html.twig' %}

{% block title %}SunuLégislatives2022 | ajputer un représentant{% endblock %}

{% block body %}
<div class="container">
    {% for message in app.flashes('success') %}
    <div class="text-center alert alert-success mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
    <div class="text-center alert alert-danger mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <div class="content">
        <div class="card">
            <div class="card-header">
                <h4>Veuillez fournir quelques informations complémentaires</h4>
            </div>
            <div class="card-body">
                {{ form_start(form, {attr: {'novalidate': 'novalidate'}}) }}
                <div class="row">
                    <div class="col-md-12">
                        {{ form_row(form.prenom) }}
                    </div>
                    <div class="col-md-12">
                        {{ form_row(form.nom) }}
                    </div>
                    <div class="col-md-12">
                        {{ form_row(form.telephone) }}
                    </div>
                    <div class="col-md-12">
                        <div class="d-flex justify-content-start">
                            <div>
                                {{ form_row(form.check) }}

                            </div>
                            <div>&nbsp;&nbsp; | </div>
                            <div>
                                <a href="{{path('app_termes_conditions')}}" class="btn btn-link"
                                    style="margin-top: -7px">Cliquer ici pour lire les
                                    termes et
                                    conditions d'utilisation</a>
                            </div>
                        </div>
                    </div>
                </div>
                <a href="{{path('app_bv_add')}}" class="btn btn-warning mt-2">Précédent</a>

                <button class="btn btn-success mt-2">{{ button_label|default('Enregistrer') }}</button>
                {{ form_end(form) }}
            </div>
        </div>


    </div>
</div>

{% endblock %}

templates/journaliste/add-lieu.html.twig
{% extends 'base.html.twig' %}

{% block title %}SunuLégislatives2022 | ajputer un représentant{% endblock %}

{% block body %}
<div class="container">
    {% for message in app.flashes('success') %}
    <div class="text-center alert alert-success mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
    <div class="text-center alert alert-danger mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <div class="content">
        <div class="card">
            <div class="card-header">
                <h4>Pour quel centre / lieu de vote, souhaitez-vous donner les résultats ?</h4>
            </div>
            <div class="card-body">
                {{ form_start(form, {attr: {'novalidate': 'novalidate'}}) }}
                {{ form_widget(form) }}
                <a href="{{path('app_circonscription_commune_add')}}" class="btn btn-warning" >Précédent</a>
                <button class="btn btn-success">{{ button_label|default('Suivant') }}</button>
                {{ form_end(form) }}
            </div>
        </div>


    </div>
</div>

{% endblock %}

templates/journaliste/bv.html.twig
{% extends 'base.html.twig' %}

{% block title %}SunuLégislatives2022 | ajouter un représentant{% endblock %}

{% block body %}
<div class="container">
    {% for message in app.flashes('success') %}
    <div class="text-center alert alert-success mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
    <div class="text-center alert alert-danger mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <div class="content">
        <div class="card">
            <div class="card-header">
                <h4>Pour quel bureau de vote, souhaitez-vous donner les résultats ?</h4>
            </div>
            <div class="card-body">
                {{ form_start(form, {attr: {'novalidate': 'novalidate'}}) }}
                {{ form_widget(form) }}
                <a href="{{path('app_journaliste_lieu_add')}}" class="btn btn-warning" >Précédent</a>
                <button class="btn btn-success">{{ button_label|default('Suivant') }}</button>
                {{ form_end(form) }}
            </div>
        </div>


    </div>
</div>

{% endblock %}

templates/journaliste/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SunuLégislatives2022 | ajouter un journaliste{% endblock %}

{% block body %}
<div class="container">
    {% for message in app.flashes('success') %}
    <div class="text-center alert alert-success mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
    <div class="text-center alert alert-danger mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <div class="content">
        <div class="card">
            <div class="card-header">
                <h4>Inscription du journaliste</h4>
            </div>
            <div class="card-body">
                {{ form_start(form, {attr: {'novalidate': 'novalidate'}}) }}
                <div class="row">
                    <div class="col-md-6">
                        {{ form_row(form.prenom) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_row(form.nom) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_row(form.telephone) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_row(form.presse) }}
                    </div>
                    <div class="col-md-12">
                        {{ form_row(form.password) }}
                    </div>
                    <div class="col-md-12">
                        <div class="d-flex justify-content-start">
                            <div>
                                {{ form_row(form.check) }}

                            </div>
                            <div>&nbsp;&nbsp; | </div>
                            <div>
                                <a href="{{path('app_termes_conditions_journaliste')}}" class="btn btn-link"
                                    style="margin-top: -7px">Cliquer ici pour lire les
                                    termes et
                                    conditions d'utilisation</a>
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-success">{{ button_label|default('S\'inscrire') }}</button>
                {{ form_end(form) }}
            </div>
        </div>


    </div>
</div>

{% endblock %}

templates/journaliste/new-confirm.html.twig
{% extends 'base.html.twig' %}

{% block title %}SunuLégislatives2022 | Importer les résultats{% endblock %}

{% block body %}

<div class="container">
    {% for message in app.flashes('success') %}
    <div class="alert alert-warning mt-2">
        {{ message }}
    </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
    <div class="text-center alert alert-danger mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <div class="content">
        <div class="card">
            <div class="card-header">
                <h4>Confirmer les résultats du bureau de vote</h4>
            </div>
            <div class="card-body">
                {{ include('resultat/_form.html.twig') }}
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/journaliste/resultat-journaliste.html.twig
{% extends 'base.html.twig' %}

{% block title %}SunuLégislatives2022 | Résultats des bureaux de vote pour chaque coalition{% endblock %}

{% block body %}


<div class="container-fluid">
    {% for message in app.flashes('success') %}
    <div class="text-center alert alert-success mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% for message in app.flashes('error') %}
    <div class="text-center alert alert-danger mt-2" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <div class="card mt-2 mb-2" style="width: 100%;">
        <div class="card-header" style="padding:20px;background-color:#fff !important;">
            <div class="d-flex justify-content-between">
                <div class="mt-2">
                    <h4>Nombre de voix de chaque Coalition par bureau de vote</h4>
                </div>
                <div>

                    <a href="{{path('app_journaliste_circonscription_add')}}" class="btn btn-success">Ajouter</a>

                    {# <a href="" class="btn btn-success">Importer le fichier</a> #}
                </div>
            </div>
        </div>

    </div>
    <div class="content table-responsive">


        {# Liste resultats rep #}
        {% if app.user and app.user.roles[0] == 'ROLE_JOURNALISTE' %}
        {% if resultats %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nom de la circonscription</th>
                    <th>Nom de la commune</th>
                    <th>Lieu/Centre de vote</th>
                    <th>Bureau de vote</th>
                    <th>Nombre d'électeurs</th>
                    <th>Nombre de votants</th>
                    <th>Bulletins nuls</th>
                    <th>Bulletins exprimés</th>
                    {% for row in coalitions %}
                    {% if row.resultatCoalitions | length > 0 %}
                    <th>
                        {{row.nom}}
                    </th>
                    {% else %}
                    <th style="display: none;"></th>
                    {% endif %}
                    {% endfor %}
                    <th>Représentant</th>

                </tr>
            </thead>
            <tbody>
                {# {% for resultat in resultats %} #}
                {% if app.user %}
                {% for resultats in resultats %}
                <tr>
                    <td> {{ resultats.user.commune.nom}} </td>
                    <td>{{ resultats.user.BV.commune.commune }}</td>
                    <td>{{ resultats.user.BV.lieu }}</td>
                    <td>{{ resultats.user.BV.NomBV }}</td>
                    <td> {{ resultats.user.BV.nbElecteur |number_format(0, '.', ' ')}} </td>
                    <td>{{ resultats.nbVotant |number_format(0, '.', ' ')}}</td>
                    <td>{{ resultats.bulletinNull |number_format(0, '.', ' ')}}</td>
                    <td>{{ resultats.bulletinExp |number_format(0, '.', ' ')}}</td>
                    {% for row in resultats.getResultatCoalitions %}
                    <td> {{row.nombre |number_format(0, '.', ' ')}} </td>
                    {% endfor %}
                    <td>{{ resultats.user.prenom }} {{resultats.user.nom}}</td>

                </tr>
                {% endfor %}
                {% endif %}
                {# {% endfor %} #}
            </tbody>
        </table>

        {% else %}
        <div class="alert alert-danger text-center" role="alert">
            <span>Aucun enregistrement trouvé </span>
        </div>
        {% endif %}
        {% endif %}

    </div>
</div>
{% endblock %}